server:
  port: 8083
spring:
  liquibase:
    change-log: classpath:/db/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/fintech
    username: postgres
    password: postgres