CREATE TYPE TRANSFER_TYPE AS ENUM ('DISBURSEMENT', 'PAYMENT');
CREATE CAST (varchar AS TRANSFER_TYPE) WITH INOUT AS IMPLICIT;

CREATE TYPE TRANSFER_STATUS AS ENUM ('IN_PROGRESS', 'FINISHED');
CREATE CAST (varchar AS TRANSFER_TYPE) WITH INOUT AS IMPLICIT;

CREATE TABLE disbursement_transfer (
    id SERIAL PRIMARY KEY,
    agreement_id INTEGER NOT NULL,
    status TRANSFER_STATUS NOT NULL
);

CREATE TABLE payment_transfer (
    id SERIAL PRIMARY KEY,
    status TRANSFER_STATUS NOT NULL,
    amount NUMERIC NOT NULL,
    balance_id VARCHAR NOT NULL
);