server:
  port: 8084

grpc:
  port: 9094
  enable-reflection: true
spring:
  liquibase:
    change-log: classpath:/db/db.changelog-master.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/fintech_origination
    username: postgres
    password: postgres
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    probes:
      enabled: true