server:
  port: 8084
grpc:
  port: 9094
  enable-reflection: true
spring:
  liquibase:
    change-log: classpath:/db/db.changelog-master.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5433/fintech_origination
    username: postgres
    password: postgres
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    probes:
      enabled: true
integration:
  product-engine:
    rest:
      url: "http://host.docker.internal:8083/"
  scoring:
    grpc:
      host: "host.docker.internal"
      port: 9094
product:
  code: "CL"
  version: "1.0"
  disbursement_amount: "40000.0"
  origination_amount: "1000.0"
  interest: "8.5"
